name: Web App Tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

# Set explicit permissions
permissions:
  contents: read

jobs:
  browser-tests:
    name: Browser Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Generate test data with reduced size
        run: |
          echo "Generating reduced test dataset..."
          python src/generate_data.py -o test_data.zarr --channels 2 --trcs 3 --samples 10000000
          echo "Test data generation complete."

      - name: Install Playwright
        run: |
          npm init -y
          npm install @playwright/test
          npx playwright install --with-deps chromium

      - name: Start local web server
        run: |
          python src/cors_server.py --port 8000 &
          echo "Web server started on port 8000"
          sleep 3  # Give the server time to start

      - name: Run browser tests
        run: npx playwright test tests/browser.spec.js
        env:
          CI: 'true'
          USE_LOCAL_DATA: 'true'
          BASE_URL: 'http://localhost:8000/website'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            *.png
          retention-days: 30
