name: Run Markdown Command Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the Markdown command check against'
        required: true
        default: 'main'

jobs:
  check-md-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Markdown Command Checker
        run: uv run ci_scripts/check_md_commands.py